---
title: "Analyse du Marché Immobilier d'Ames"
subtitle: "Rapport de projet · Visualisation de Données · Data Science / IA UFHB.UFRMI"
author: |
  | CAMARA Massaram & LOGBO Axelle · Groupe 4
  | \vspace{2pt} \small Sous l'encadrement du **Dr.KACOUTCHY Jean Ayikpa**
date: "Juillet 2026"
output:
  pdf_document:
    toc: true
    toc_depth: 2
    number_sections: true
    latex_engine: xelatex
lang: fr
fontsize: 11pt
geometry: margin=1.9cm
urlcolor: orangeames
linkcolor: marineames
header-includes:
  - \usepackage{setspace}
  - \setstretch{1.05}
  - \usepackage{float}
  - \usepackage{xcolor}
  - \definecolor{orangeames}{HTML}{E8721C}
  - \definecolor{marineames}{HTML}{102A43}
  - \usepackage{sectsty}
  - \sectionfont{\color{marineames}}
  - \subsectionfont{\color{marineames}}
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \setlength{\headheight}{13pt}
  - \fancyhf{}
  - \fancyhead[L]{\small\color{gray}Marché immobilier d'Ames · Master 1 Groupe 4}
  - \fancyhead[R]{\small\color{gray}UFHB · UFRMI · 2025-2026}
  - \fancyfoot[C]{\thepage}
  - \renewcommand{\headrulewidth}{0.4pt}
  - \renewcommand{\headrule}{\color{orangeames}\hrule width\headwidth height 0.8pt}
  - \usepackage{titling}
  - \pretitle{\begin{center}\color{marineames}\Huge\bfseries}
  - \posttitle{\par\vskip 4pt{\color{orangeames}\rule{0.35\textwidth}{2pt}}\end{center}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,
                      fig.align = "center", out.width = "80%",
                      fig.pos = "H")
library(ggplot2)
library(dplyr)
library(scales)
library(here)
library(kableExtra)
train <- read.csv(here("data", "train_clean.csv"), stringsAsFactors = FALSE)
```

\newpage
```{r child="01-presentation.Rmd"}
```

```{r child="02-donnees.Rmd"}
```

\newpage

```{r child="03-nettoyage.Rmd"}
```

```{r child="04-analyse.Rmd"}
```

```{r child="05-modelisation.Rmd"}
```

```{r child="dashboard.Rmd"}
```

```{r child="06-recommandations.Rmd"}
```

\newpage

```{r child="08-organisation.Rmd"}
```

\newpage

```{r child="07-catalogue.Rmd"}
```